[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Scheduled function for booking timeouts
[[functions]]
  name = "booking-timeout-handler"
  path = "netlify/functions/booking-timeout-handler.js"
  schedule = "*/5 * * * *"  # Run every 5 minutes

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
